# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeLoveCats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeLoveCats

  target 'WeLoveCatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeLoveCatsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
